//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Podgotovka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.ProductSale = new HashSet<ProductSale>();
        }
    
        public int ID { get; set; }
        public string AgentType { get; set; }
        public string AgentName { get; set; }
        public string AgentMail { get; set; }
        public string AgentPhone { get; set; }
        public string AgentLogoImage { get; set; }
        public string AgentAddress { get; set; }
        public int AgetntPriority { get; set; }
        public string AgentDirector { get; set; }
        public string AgentTIN { get; set; }
        public string AgentCIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
    }
}
